### ISSUE TITLE
How to match multiple times on a single line

### ISSUE THREAD

**Issue by markfaine** [DomiR/vscode-regreplace#2]
The following works on a regular html file with new line chars:

```
    {
      "match": ".htm[l]$",
      "regexp": "(')(.*)(')",
      "global": true,
      "replace": "\"$2\""
    }
```

However, if the file is minimized and on one line it doesn't work.  It only replaces the first occurrence.  It seems there needs to be some way to do a global match. The documentation seems to indicate that global in this context doesn't mean what it usually means for regexp.

**Comment by DomiR** [comment]
Hey, thanks for using my plugin 👍 
This is how regex works, as it is will replace all matches, but with your setting it will only find one result...

```html
<h1 nice="what">My First Heading</h1><p hello="no">My first paragraph.<p>

<!-- will be replaced by -->
<h1 nice='what">My First Heading</h1><p hello="no'>My first paragraph.<p>

<!-- below is your first and only match -->
what">My First Heading</h1><p hello="no
```

You probably want:
```json
    {
      "match": ".htm[l]$",
      "regexp": "(')(.*?)(')",
      "global": true,
      "replace": "\"$2\""
    }
```
Please look up `non greedy modifier`
https://stackoverflow.com/questions/11898998/how-can-i-write-a-regex-which-matches-non-greedy
