### ISSUE TITLE
VSCode commands for individual rules

### ISSUE THREAD

**Issue by iammoen** [DomiR/vscode-regreplace#4]
I could just be a dunce but I don't see the custom commands being registered with VSCode as commands that can be run individually?

**Comment by DomiR** [comment]
Hey @iammoen, this is not implemented yet, but I will look into it ☺️ 

https://code.visualstudio.com/docs/extensionAPI/vscode-api#commands.registerCommand

**Comment by iammoen** [comment]
Ah ok! That would be super. I loved the regreplace on sublime text and was super pumped about your project. If I have time to learn about vscode extensions a bit more maybe I could even help.

**Comment by DomiR** [comment]
This should be fixed now 🎉  Please test the beta via [Beta installation](https://github.com/DomiR/vscode-regreplace/wiki/Installing-Beta-Releases).

I would like to release the update next week, if you can test it, please report back issues.

**Comment by iammoen** [comment]
I totally understand if this is a technical block that can't be remedied, but in sublime text you could open the command palette and immediately start typing / searching for the command. In your update you have "Run Single Rule" that you need to select first. Which totally works by the way. And I like how you have the number preceding the command for easy execution. Just one additional step in this workflow. Which I almost feel guilty even bringing up since you made this sweet plugin.

**Comment by DomiR** [comment]
Thanks for the input. I will leave it for now, as it would be quite a bit of work to add and remove the commands on every config change. I think the current way is what the extension guidelines would want us to use. You should be able to run a command via keyboard shortcut and open the selection directly... If this is not possible, I you may reopen this issue.
