### ISSUE TITLE
[feature request] Associate rules with languages

### ISSUE THREAD

**Issue by atnbueno** [DomiR/vscode-regreplace#5]
Would it be too much work to associate the rules to languages (as determined by VSCode) in addition or instead of file types?

It would probably be cleaner/clearer than needing a complex "match" regex.

**Comment by DomiR** [comment]
This should work now 🎉  Please test the beta via [Beta installation](https://github.com/DomiR/vscode-regreplace/wiki/Installing-Beta-Releases).

I would like to release the update next week, if you can test it, please report back issues.

**Comment by atnbueno** [comment]
Tested. No problems. Thanks a lot! 😄
