### ISSUE TITLE
[documentation] Regex examples improperly escaped

### ISSUE THREAD

**Issue by atnbueno** [DomiR/vscode-regreplace#6]
The regexes that appear in the examples should have the `\` escaped (`\\`) because they are used with the [constructor function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Description). For example, VSCode shows the `\.` in `"\.(ts|js|tsx)$"` as an error, and it only works if it is changed to `"\\.(ts|js|tsx)$"`.

**Comment by DomiR** [comment]
I think this is fixed in the Readme on this repo?! 

Otherwise please open a pull request (you probably know this, but you can also do it online here: https://github.com/DomiR/vscode-regreplace/edit/master/README.md)

**Comment by atnbueno** [comment]
Done: https://github.com/DomiR/vscode-regreplace/pull/7
