### ISSUE TITLE
[Question] what flavor of regex?

### ISSUE THREAD

**Issue by Geobert** [DomiR/vscode-regreplace#8]
I'm trying to do this: https://stackoverflow.com/questions/50605114/regex-to-match-a-char-if-not-inside-a-markdown-code-block

So I was wondering which kind of regex this plugin uses?

**Comment by DomiR** [comment]
Hey, it's regular Javascript regex :)

**Comment by DomiR** [comment]
Hey, it's regular Javascript regex :)
